### ISSUE TITLE
Latest version cannot be installed on AMO

### ISSUE THREAD

**Issue by silverwind** [OverByThere/firefox-ip-check#1]
It seems the install button on https://addons.mozilla.org/en-US/firefox/addon/ip-check/ does not work, maybe it needs republishing?

**Comment by DanClarke-io** [comment]
Hi @silverwind, I've now sent this through to be re-approved using the latest build requirements. It doesn't yet work on multi-thread, which is why I've delayed any further updates.

This should be online sometime later today, hope that's okay!

Once it is, if you are able to see if it downloads (I will too) and let me know here, just to close it all off.

Dan.

**Comment by silverwind** [comment]
I was just able to install from AMO, thanks again!
